// src/QueryManager.js

import ApolloClient from 'apollo-boost';
import gql from 'graphql-tag';

var apolloClient = null;

const runQuery = async (query) => {
    if (!apolloClient) {
        throw new Error("ApolloClient didn't initialized.");
    }

    const result = await apolloClient.query({
        query: gql`
            ${query}
        `,
    });

    // Extract result data from the result
    const resultData = Object.values(result.data)[0];

    // Delete '__typename' field generated by GraphQL
    if (Array.isArray(resultData)) {
        resultData.map((item) => {
            delete item.__typename;
        });
    } else if(typeof(resultData) === 'object') {
        delete resultData.__typename;
    }

    return resultData;
};

const QueryManager = {
    initialize: (endpoint) => {
        apolloClient = new ApolloClient({
            uri: endpoint,
        });
    },

    query: async (query) => {
        return await runQuery(query);
    },
};

export default QueryManager;
